/* Redaura i18n runtime — zero-dependency, flat i18next-style keys.
   Source of truth: locales/en.json (authored in English).
   All other locale files are GENERATED by tools/translate.mjs — never hand-edit them.
   data-i18n="key"      → textContent swap
   data-i18n-html="key" → innerHTML swap (for strings carrying <b>/<br>)
   Emits `redaura:lang` (detail: {code, t}) and forwards the code to the app iframe. */
(() => {
  const LS = 'redaura-lang';
  const state = { code: 'en', dict: null, fallback: null };
  const load = async (path) => {
    try { const r = await fetch('locales/' + path); return r.ok ? await r.json() : null; }
    catch { return null; }
  };
  const t = (k) => {
    if (state.dict && state.dict[k] != null) return state.dict[k];
    return state.fallback ? state.fallback[k] : undefined;
  };
  const syncFrame = () => {
    const frame = document.querySelector('.app-frame');
    if (frame && frame.contentWindow) frame.contentWindow.postMessage({ t: 'redaura-lang', code: state.code }, '*');
  };
  const apply = () => {
    document.documentElement.lang = state.code;
    document.documentElement.dir = ['ar'].includes(state.code) ? 'rtl' : 'ltr';
    const title = t('meta.title');
    if (title) document.title = title;
    document.querySelectorAll('[data-i18n]').forEach((el) => {
      const v = t(el.dataset.i18n);
      if (v != null) el.textContent = v;
    });
    document.querySelectorAll('[data-i18n-html]').forEach((el) => {
      const v = t(el.dataset.i18nHtml);
      if (v != null) el.innerHTML = v;
    });
    dispatchEvent(new CustomEvent('redaura:lang', { detail: { code: state.code, t } }));
    syncFrame();
  };
  const set = async (code) => {
    if (!state.fallback) state.fallback = await load('en.json');
    state.dict = code === 'en' ? state.fallback : await load(code + '.json');
    state.code = state.dict ? code : 'en';
    try { localStorage.setItem(LS, state.code); } catch {}
    const sel = document.getElementById('lang-select');
    if (sel) sel.value = state.code;
    const codeEl = document.getElementById('lang-code');
    if (codeEl) codeEl.textContent = state.code.toUpperCase();
    apply();
  };
  const init = async () => {
    const langs = (await load('manifest.json')) || [{ code: 'en', label: 'English' }];
    const known = new Set(langs.map((l) => l.code));
    const sel = document.getElementById('lang-select');
    if (sel) {
      sel.innerHTML = langs.map((l) => '<option value="' + l.code + '">' + l.label + '</option>').join('');
      sel.addEventListener('change', () => set(sel.value));
    }
    let saved = null;
    try { saved = localStorage.getItem(LS); } catch {}
    const detect = () => {
      for (const l of navigator.languages || [navigator.language]) {
        const base = String(l).toLowerCase().split('-')[0];
        if (known.has(base)) return base;
      }
      return 'en';
    };
    const frame = document.querySelector('.app-frame');
    if (frame) frame.addEventListener('load', syncFrame);
    await set(saved && known.has(saved) ? saved : detect());
  };
  window.redauraI18n = { set, t };
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
  else init();
})();
